### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by sharifnezhad**
Hello
It's a shame that this great tool can't be used in Laravel 9.
That's why I decided to make some changes so that those using Laravel 9 can benefit from this tool.
**The changes that have been made are:**
1. Upgrade the php version
2. Add version 9 to illuminate/routing, illuminate/routing, illuminate/console

### CODE REVIEW

**Comment by ossycodes** [comment]
@ovac how far baba ? any updates concerning Laravel 9

**Comment by ovac** [comment]
@ossycodes @sharifnezhad Thank you for this update. I will release a new version immediately to support Laravel 9.

**Comment by ossycodes** [comment]
@ovac seems you made a mistake in the release version (you did 1.5.0 instead of v.1.5.0)

**Comment by ossycodes** [comment]
> @ovac seems you made a mistake in the release version (you did 1.5.0 instead of v.1.5.0)

@ovac please check

**Pull request merged**
